---
- apt:
    pkg: unzip
    state: latest

- get_url:
    url: "https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip"
    dest: /tmp/consul.zip

- unarchive:
    src: /tmp/consul.zip
    dest: /usr/local/bin
    copy: no
